# Generated by Django 3.0.4 on 2020-04-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagerapp', '0002_auto_20200407_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Data',
        ),
    ]
