# Generated by Django 3.0.4 on 2020-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagerapp', '0003_auto_20200407_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='check',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
