# Generated by Django 3.0.4 on 2020-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagerapp', '0005_auto_20200408_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='etype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
